# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        Music\SecurityBundle\Entity\User: bcrypt

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        custom_user_provider:
            id: music.security.provider.user

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            guard:
                authenticators:
                    - music.security.authenticator.token
            provider: custom_user_provider
            form_login:
                login_path: homepage
                check_path: login_check
                success_handler: music.security.handler.login.success
                failure_handler: music.security.handler.login.fail
            logout:
                path: /logout